// Copyright (c) CLMS UK. All rights reserved.
// Licensed under the Custom License. See LICENSE file in the project root for full license information.
// This was autogenerated by zAppDev.
using System;
using System.Runtime.Serialization;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Collections;
using System.ComponentModel.DataAnnotations;
using System.Linq.Expressions;
using zAppDev.DotNet.Framework.Linq;
using zAppDev.DotNet.Framework.Data.Domain;
using zAppDev.DotNet.Framework.Workflow;
using zAppDev.DotNet.Framework.Identity.Model;

namespace DigicircMatchmaking.BO
{
    /// <summary>
    /// The Product class
    ///
    /// </summary>
    [Serializable]
    [DataContract]
    public class Product : IDomainModelClass
    {
        #region Product's Fields

        protected Guid _transientId= Guid.NewGuid();
        public virtual Guid TransientId
        {
            get
            {
                return _transientId;
            }
            set
            {
                _transientId = value;
            }
        }
        [DataMember(Name="Id")]
        protected int? id = 0;
        [DataMember(Name="Quantity")]
        protected int? quantity;
        [DataMember(Name="ValidFrom")]
        protected DateTime? validFrom;
        [DataMember(Name="ValidTo")]
        protected DateTime? validTo;
        [DataMember(Name="IsHazardous")]
        protected bool isHazardous;
        [DataMember(Name="IsDesired")]
        protected bool isDesired;
        [DataMember(Name="VersionTimestamp")]
        protected int? versionTimestamp;

        #endregion
        #region Product's Properties
/// <summary>
/// The Id property
///
/// </summary>
///
        [Key]
        public virtual int? Id
        {
            get
            {
                return id;
            }
            set
            {
                id = value;
            }
        }
/// <summary>
/// The Quantity property
///
/// </summary>
///
        public virtual int? Quantity
        {
            get
            {
                return quantity;
            }
            set
            {
                quantity = value;
            }
        }
/// <summary>
/// The ValidFrom property
///
/// </summary>
///
        public virtual DateTime? ValidFrom
        {
            get
            {
                return validFrom;
            }
            set
            {
                validFrom = value;
            }
        }
/// <summary>
/// The ValidTo property
///
/// </summary>
///
        public virtual DateTime? ValidTo
        {
            get
            {
                return validTo;
            }
            set
            {
                validTo = value;
            }
        }
/// <summary>
/// The IsHazardous property
///
/// </summary>
///
        public virtual bool IsHazardous
        {
            get
            {
                return isHazardous;
            }
            set
            {
                isHazardous = value;
            }
        }
/// <summary>
/// The IsDesired property
///
/// </summary>
///
        public virtual bool IsDesired
        {
            get
            {
                return isDesired;
            }
            set
            {
                isDesired = value;
            }
        }
/// <summary>
/// The VersionTimestamp property
///Provides concurrency control for the class
/// </summary>
///
        public virtual int? VersionTimestamp
        {
            get
            {
                return versionTimestamp;
            }
            set
            {
                versionTimestamp = value;
            }
        }
        #endregion
        #region Product's Participant Properties
        [DataMember(Name="Resource")]
        protected Material resource;
        public virtual Material Resource
        {
            get
            {
                return resource;
            }
            set
            {
                if(Equals(resource, value)) return;
                var __oldValue = resource;
                resource = value;
            }
        }
        [DataMember(Name="Type")]
        protected ProductType type;
        public virtual ProductType Type
        {
            get
            {
                return type;
            }
            set
            {
                if(Equals(type, value)) return;
                var __oldValue = type;
                type = value;
            }
        }
        [DataMember(Name="Site")]
        protected Address site;
        public virtual Address Site
        {
            get
            {
                return site;
            }
            set
            {
                if(Equals(site, value)) return;
                var __oldValue = site;
                site = value;
            }
        }
        [DataMember(Name="UnitOfMeasurement")]
        protected UnitOfMeasurement unitOfMeasurement;
        public virtual UnitOfMeasurement UnitOfMeasurement
        {
            get
            {
                return unitOfMeasurement;
            }
            set
            {
                if(Equals(unitOfMeasurement, value)) return;
                var __oldValue = unitOfMeasurement;
                unitOfMeasurement = value;
            }
        }
        [DataMember(Name="PhysicalForm")]
        protected PhysicalForm physicalForm;
        public virtual PhysicalForm PhysicalForm
        {
            get
            {
                return physicalForm;
            }
            set
            {
                if(Equals(physicalForm, value)) return;
                var __oldValue = physicalForm;
                physicalForm = value;
            }
        }
        #endregion
        #region Constructors
/// <summary>
/// Public constructors of the Product class
/// </summary>
/// <returns>New Product object</returns>
/// <remarks></remarks>
        public Product() {}
        #endregion
        #region Methods

        public virtual List<string> _Validate(bool throwException = true)
        {
            var __errors = new List<string>();
            if (Id == null)
            {
                __errors.Add("Property 'Id' is required.");
            }
            if (throwException && __errors.Any())
            {
                throw new zAppDev.DotNet.Framework.Exceptions.BusinessException("An instance of TypeClass 'Product' has validation errors:\r\n\r\n" + string.Join("\r\n", __errors));
            }
            return __errors;
        }

        public virtual int _GetUniqueIdentifier()
        {
            var hashCode = 399326290;
            hashCode = hashCode * -1521134295 + (Id?.GetHashCode() ?? 0);
            hashCode = hashCode * -1521134295 + (Quantity?.GetHashCode() ?? 0);
            hashCode = hashCode * -1521134295 + (ValidFrom?.GetHashCode() ?? 0);
            hashCode = hashCode * -1521134295 + (ValidTo?.GetHashCode() ?? 0);
            hashCode = hashCode * -1521134295 + (IsHazardous.GetHashCode() );
            hashCode = hashCode * -1521134295 + (IsDesired.GetHashCode() );
            return hashCode;
        }






/// <summary>
/// Copies the current object to a new instance
/// </summary>
/// <param name="deep">Copy members that refer to objects external to this class (not dependent)</param>
/// <param name="copiedObjects">Objects that should be reused</param>
/// <param name="asNew">Copy the current object as a new one, ready to be persisted, along all its members.</param>
/// <param name="reuseNestedObjects">If asNew is true, this flag if set, forces the reuse of all external objects.</param>
/// <param name="copy">Optional - An existing [Product] instance to use as the destination.</param>
/// <returns>A copy of the object</returns>
        public virtual Product Copy(bool deep=false, Hashtable copiedObjects=null, bool asNew=false, bool reuseNestedObjects = false, Product copy = null)
        {
            if(copiedObjects == null)
            {
                copiedObjects = new Hashtable();
            }
            if (copy == null && copiedObjects.Contains(this))
                return (Product)copiedObjects[this];
            copy = copy ?? new Product();
            if (!asNew)
            {
                copy.TransientId = this.TransientId;
                copy.Id = this.Id;
            }
            copy.Quantity = this.Quantity;
            copy.ValidFrom = this.ValidFrom;
            copy.ValidTo = this.ValidTo;
            copy.IsHazardous = this.IsHazardous;
            copy.IsDesired = this.IsDesired;
            if (!copiedObjects.Contains(this))
            {
                copiedObjects.Add(this, copy);
            }
            if(deep && this.resource != null)
            {
                if (!copiedObjects.Contains(this.resource))
                {
                    if (asNew && reuseNestedObjects)
                        copy.Resource = this.Resource;
                    else if (asNew)
                        copy.Resource = this.Resource.Copy(deep, copiedObjects, true);
                    else
                        copy.resource = this.resource.Copy(deep, copiedObjects, false);
                }
                else
                {
                    if (asNew)
                        copy.Resource = (Material)copiedObjects[this.Resource];
                    else
                        copy.resource = (Material)copiedObjects[this.Resource];
                }
            }
            if(deep && this.type != null)
            {
                if (!copiedObjects.Contains(this.type))
                {
                    if (asNew && reuseNestedObjects)
                        copy.Type = this.Type;
                    else if (asNew)
                        copy.Type = this.Type.Copy(deep, copiedObjects, true);
                    else
                        copy.type = this.type.Copy(deep, copiedObjects, false);
                }
                else
                {
                    if (asNew)
                        copy.Type = (ProductType)copiedObjects[this.Type];
                    else
                        copy.type = (ProductType)copiedObjects[this.Type];
                }
            }
            if(deep && this.site != null)
            {
                if (!copiedObjects.Contains(this.site))
                {
                    if (asNew && reuseNestedObjects)
                        copy.Site = this.Site;
                    else if (asNew)
                        copy.Site = this.Site.Copy(deep, copiedObjects, true);
                    else
                        copy.site = this.site.Copy(deep, copiedObjects, false);
                }
                else
                {
                    if (asNew)
                        copy.Site = (Address)copiedObjects[this.Site];
                    else
                        copy.site = (Address)copiedObjects[this.Site];
                }
            }
            if(deep && this.unitOfMeasurement != null)
            {
                if (!copiedObjects.Contains(this.unitOfMeasurement))
                {
                    if (asNew && reuseNestedObjects)
                        copy.UnitOfMeasurement = this.UnitOfMeasurement;
                    else if (asNew)
                        copy.UnitOfMeasurement = this.UnitOfMeasurement.Copy(deep, copiedObjects, true);
                    else
                        copy.unitOfMeasurement = this.unitOfMeasurement.Copy(deep, copiedObjects, false);
                }
                else
                {
                    if (asNew)
                        copy.UnitOfMeasurement = (UnitOfMeasurement)copiedObjects[this.UnitOfMeasurement];
                    else
                        copy.unitOfMeasurement = (UnitOfMeasurement)copiedObjects[this.UnitOfMeasurement];
                }
            }
            if(deep && this.physicalForm != null)
            {
                if (!copiedObjects.Contains(this.physicalForm))
                {
                    if (asNew && reuseNestedObjects)
                        copy.PhysicalForm = this.PhysicalForm;
                    else if (asNew)
                        copy.PhysicalForm = this.PhysicalForm.Copy(deep, copiedObjects, true);
                    else
                        copy.physicalForm = this.physicalForm.Copy(deep, copiedObjects, false);
                }
                else
                {
                    if (asNew)
                        copy.PhysicalForm = (PhysicalForm)copiedObjects[this.PhysicalForm];
                    else
                        copy.physicalForm = (PhysicalForm)copiedObjects[this.PhysicalForm];
                }
            }
            return copy;
        }

        public override bool Equals(object obj)
        {
            var compareTo = obj as Product;
            if (ReferenceEquals(this, compareTo))
            {
                return true;
            }
            if (compareTo == null || !this.GetType().Equals(compareTo.GetTypeUnproxied()))
            {
                return false;
            }
            if (this.HasSameNonDefaultIdAs(compareTo))
            {
                return true;
            }
            // Since the Ids aren't the same, both of them must be transient to
            // compare domain signatures; because if one is transient and the
            // other is a persisted entity, then they cannot be the same object.
            return this.IsTransient() && compareTo.IsTransient() && (base.Equals(compareTo) || this.TransientId.Equals(compareTo.TransientId));
        }

// Maintain equality operator semantics for entities.
        public static bool operator ==(Product x, Product y)
        {
            // By default, == and Equals compares references. In order to
            // maintain these semantics with entities, we need to compare by
            // identity value. The Equals(x, y) override is used to guard
            // against null values; it then calls EntityEquals().
            return Equals(x, y);
        }

// Maintain inequality operator semantics for entities.
        public static bool operator !=(Product x, Product y)
        {
            return !(x == y);
        }

        private PropertyInfo __propertyKeyCache;
        public virtual PropertyInfo GetPrimaryKey()
        {
            if (__propertyKeyCache == null)
            {
                __propertyKeyCache = this.GetType().GetProperty("Id");
            }
            return __propertyKeyCache;
        }


/// <summary>
///     To help ensure hashcode uniqueness, a carefully selected random number multiplier
///     is used within the calculation.  Goodrich and Tamassia's Data Structures and
///     Algorithms in Java asserts that 31, 33, 37, 39 and 41 will produce the fewest number
///     of collissions.  See http://computinglife.wordpress.com/2008/11/20/why-do-hash-functions-use-prime-numbers/
///     for more information.
/// </summary>
        private const int HashMultiplier = 31;
        private int? cachedHashcode;

        public override int GetHashCode()
        {
            if (this.cachedHashcode.HasValue)
            {
                return this.cachedHashcode.Value;
            }
            if (this.IsTransient())
            {
                //this.cachedHashcode = base.GetHashCode();
                return this.TransientId.GetHashCode(); //don't cache because this won't stay transient forever
            }
            else
            {
                unchecked
                {
                    // It's possible for two objects to return the same hash code based on
                    // identically valued properties, even if they're of two different types,
                    // so we include the object's type in the hash calculation
                    var hashCode = this.GetType().GetHashCode();
                    this.cachedHashcode = (hashCode * HashMultiplier) ^ this.Id.GetHashCode();
                }
            }
            return this.cachedHashcode.Value;
        }

/// <summary>
///     Transient objects are not associated with an item already in storage.  For instance,
///     a Customer is transient if its Id is 0.  It's virtual to allow NHibernate-backed
///     objects to be lazily loaded.
/// </summary>
        public virtual bool IsTransient()
        {
            return this.Id == default(int) || this.Id.Equals(default(int));
        }

/// <summary>
///     When NHibernate proxies objects, it masks the type of the actual entity object.
///     This wrapper burrows into the proxied object to get its actual type.
///
///     Although this assumes NHibernate is being used, it doesn't require any NHibernate
///     related dependencies and has no bad side effects if NHibernate isn't being used.
///
///     Related discussion is at http://groups.google.com/group/sharp-architecture/browse_thread/thread/ddd05f9baede023a ...thanks Jay Oliver!
/// </summary>
        protected virtual System.Type GetTypeUnproxied()
        {
            return this.GetType();
        }

/// <summary>
///     Returns true if self and the provided entity have the same Id values
///     and the Ids are not of the default Id value
/// </summary>
        protected bool HasSameNonDefaultIdAs(Product compareTo)
        {
            return !this.IsTransient() && !compareTo.IsTransient() && this.Id.Equals(compareTo.Id);
        }

        #endregion


    }
}
