// Copyright (c) CLMS UK. All rights reserved.
// Licensed under the Custom License. See LICENSE file in the project root for full license information.
// This was autogenerated by zAppDev.
using System;
using System.Runtime.Serialization;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Collections;
using zAppDev.DotNet.Framework.Data.Domain;

namespace DigicircMatchmaking.BO
{

/// <summary>
/// The StorageMedium class
///
/// </summary>
    [Serializable]
    [DataContract]
    public enum StorageMedium
    {
        [DataMember(Name="FileSystem")]
        FileSystem,
        [DataMember(Name="DataBase")]
        DataBase,
    }
}