var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
// Copyright (c) CLMS UK. All rights reserved.
// Licensed under the Custom License. See LICENSE file in the project root for full license information.
// This was autogenerated by zAppDev.
var DigicircMatchmaking;
(function (DigicircMatchmaking) {
    var ViewModels;
    (function (ViewModels) {
        var EntityTypeForm;
        (function (EntityTypeForm) {
            var EntityTypeFormViewModel = /** @class */ (function (_super) {
                __extends(EntityTypeFormViewModel, _super);
                function EntityTypeFormViewModel() {
                    return _super.call(this) || this;
                }
                EntityTypeFormViewModel._lightCast = function (instance) {
                    if (instance == null)
                        return;
                    if (instance.EntityType != null)
                        instance.EntityType = EntityType_EntityTypeViewModel._lightCast(instance.EntityType);
                    return instance;
                };
                EntityTypeFormViewModel._initializeFrom = function (original, ignoreReadOnlyProperties, context) {
                    if (ignoreReadOnlyProperties === void 0) { ignoreReadOnlyProperties = false; }
                    if (context === void 0) { context = new Joove.DTOHelper(); }
                    if (original == null)
                        return null;
                    // if (context.Has(original)) {
                    //    return context.Get(original);
                    // }
                    var result = new EntityTypeFormViewModel();
                    if (context != null && context.fillDb == true) {
                        context.addToDb(original);
                    }
                    result._hydrateEntityTypeFormViewModel(original, ignoreReadOnlyProperties, context);
                    // context.Add(original, result);
                    return result;
                };
                EntityTypeFormViewModel.prototype._hydrateEntityTypeFormViewModel = function (original, ignoreReadOnlyProperties, context) {
                    if (context === void 0) { context = new Joove.DTOHelper(); }
                    if (original == null)
                        return;
                    this._hydrateMasterPageViewModel(original, ignoreReadOnlyProperties, context);
                    if (original._key !== undefined)
                        this._key = original._key;
                    if (original._clientKey !== undefined)
                        this._clientKey = original._clientKey;
                    if (original._originalTypeClassName !== undefined)
                        this._originalTypeClassName = original._originalTypeClassName;
                    if (original._typeHash !== undefined)
                        this._typeHash = original._typeHash;
                    if (original.EntityType !== undefined)
                        this.EntityType = EntityType_EntityTypeViewModel._initializeFrom(original.EntityType, ignoreReadOnlyProperties, context);
                    this._reduceData = function (ignoreReadOnlyProperties) {
                        var reduced = EntityTypeFormViewModel._initializeFrom(this, ignoreReadOnlyProperties);
                        EntityTypeFormViewModel._deleteDropDownInitialValues(reduced);
                        return reduced;
                    };
                }; /* end _initializeFrom() */
                EntityTypeFormViewModel.prototype._reduceData = function (ignoreReadOnlyProperties) {
                    var reduced = EntityTypeFormViewModel._initializeFrom(this, ignoreReadOnlyProperties);
                    EntityTypeFormViewModel._deleteDropDownInitialValues(reduced);
                    return reduced;
                };
                EntityTypeFormViewModel._deleteDropDownInitialValues = function (reduced) {
                    if (reduced == null)
                        return;
                    DigicircMatchmaking.ViewModels.MasterPage.MasterPageViewModel._deleteDropDownInitialValues(reduced);
                };
                return EntityTypeFormViewModel;
            }(DigicircMatchmaking.ViewModels.MasterPage.MasterPageViewModel));
            EntityTypeForm.EntityTypeFormViewModel = EntityTypeFormViewModel;
            var EntityType_EntityTypeViewModel = /** @class */ (function (_super) {
                __extends(EntityType_EntityTypeViewModel, _super);
                function EntityType_EntityTypeViewModel() {
                    return _super.call(this) || this;
                }
                EntityType_EntityTypeViewModel._lightCast = function (instance) {
                    if (instance == null)
                        return;
                    return instance;
                };
                EntityType_EntityTypeViewModel._initializeFrom = function (original, ignoreReadOnlyProperties, context) {
                    if (ignoreReadOnlyProperties === void 0) { ignoreReadOnlyProperties = false; }
                    if (context === void 0) { context = new Joove.DTOHelper(); }
                    if (original == null)
                        return null;
                    // if (context.Has(original)) {
                    //    return context.Get(original);
                    // }
                    var result = new EntityType_EntityTypeViewModel();
                    if (context != null && context.fillDb == true) {
                        context.addToDb(original);
                    }
                    result._hydrateEntityType_EntityTypeViewModel(original, ignoreReadOnlyProperties, context);
                    // context.Add(original, result);
                    return result;
                };
                EntityType_EntityTypeViewModel.prototype._hydrateEntityType_EntityTypeViewModel = function (original, ignoreReadOnlyProperties, context) {
                    if (context === void 0) { context = new Joove.DTOHelper(); }
                    if (original == null)
                        return;
                    if (original._key !== undefined)
                        this._key = original._key;
                    if (original._clientKey !== undefined)
                        this._clientKey = original._clientKey;
                    if (original._originalTypeClassName !== undefined)
                        this._originalTypeClassName = original._originalTypeClassName;
                    if (original._typeHash !== undefined)
                        this._typeHash = original._typeHash;
                    if (original.Code !== undefined)
                        this.Code = original.Code;
                    if (original.Id !== undefined)
                        this.Id = original.Id;
                    if (original.IsCluster !== undefined)
                        this.IsCluster = original.IsCluster;
                    if (original.IsProvider !== undefined)
                        this.IsProvider = original.IsProvider;
                    if (original.Value !== undefined)
                        this.Value = original.Value;
                    this._reduceData = function (ignoreReadOnlyProperties) {
                        var reduced = EntityType_EntityTypeViewModel._initializeFrom(this, ignoreReadOnlyProperties);
                        return reduced;
                    };
                }; /* end _initializeFrom() */
                EntityType_EntityTypeViewModel.prototype._reduceData = function (ignoreReadOnlyProperties) {
                    var reduced = EntityType_EntityTypeViewModel._initializeFrom(this, ignoreReadOnlyProperties);
                    return reduced;
                };
                return EntityType_EntityTypeViewModel;
            }(BaseClass.ViewModel));
            EntityTypeForm.EntityType_EntityTypeViewModel = EntityType_EntityTypeViewModel;
        })(EntityTypeForm = ViewModels.EntityTypeForm || (ViewModels.EntityTypeForm = {}));
    })(ViewModels = DigicircMatchmaking.ViewModels || (DigicircMatchmaking.ViewModels = {}));
})(DigicircMatchmaking || (DigicircMatchmaking = {}));
