// Copyright (c) CLMS UK. All rights reserved.
// Licensed under the Custom License. See LICENSE file in the project root for full license information.
// This was autogenerated by zAppDev.
namespace DigicircMatchmaking.ViewModels.PhysicalFormForm {
export class PhysicalFormFormViewModel extends DigicircMatchmaking.ViewModels.SymbiosisMasterPage.SymbiosisMasterPageViewModel {
    public constructor() {
        super();
    }


    public static _lightCast(instance: any): any {
        if (instance == null) return;

        if(instance.PhysicalForm != null)
            instance.PhysicalForm = PhysicalForm_PhysicalFormViewModel._lightCast(instance.PhysicalForm);
        return instance;
    }

    public static _initializeFrom(original: PhysicalFormFormViewModel, ignoreReadOnlyProperties: boolean = false, context = new Joove.DTOHelper()): PhysicalFormFormViewModel {
        if(original == null) return null;
        // if (context.Has(original)) {
        //    return context.Get(original);
        // }
var result:
        PhysicalFormFormViewModel = new PhysicalFormFormViewModel();
        if (context != null && context.fillDb == true) {
            context.addToDb(original);
        }
        result._hydratePhysicalFormFormViewModel(original, ignoreReadOnlyProperties, context);
        // context.Add(original, result);
        return result;
    }


    public _hydratePhysicalFormFormViewModel(original: PhysicalFormFormViewModel, ignoreReadOnlyProperties: boolean, context = new Joove.DTOHelper()): void {
        if(original == null) return;

        this._hydrateSymbiosisMasterPageViewModel(original, ignoreReadOnlyProperties, context);

        if(original._key !== undefined) this._key = original._key;
        if(original._clientKey !== undefined) this._clientKey = original._clientKey;
        if(original._originalTypeClassName !== undefined) this._originalTypeClassName = original._originalTypeClassName;
        if(original._typeHash !== undefined) this._typeHash = original._typeHash;


        if(original.PhysicalForm !== undefined) this.PhysicalForm = PhysicalForm_PhysicalFormViewModel._initializeFrom(original.PhysicalForm, ignoreReadOnlyProperties, context);

        this._reduceData = function(ignoreReadOnlyProperties: boolean) {
            var reduced = PhysicalFormFormViewModel._initializeFrom(this, ignoreReadOnlyProperties);
            PhysicalFormFormViewModel._deleteDropDownInitialValues(reduced);
            return reduced;
        };
    } /* end _initializeFrom() */


    public _reduceData(ignoreReadOnlyProperties: boolean): PhysicalFormFormViewModel {
        var reduced = PhysicalFormFormViewModel._initializeFrom(this, ignoreReadOnlyProperties);
        PhysicalFormFormViewModel._deleteDropDownInitialValues(reduced);
        return reduced;
    }

    public static _deleteDropDownInitialValues(reduced: PhysicalFormFormViewModel) {
        if (reduced == null) return;


        DigicircMatchmaking.ViewModels.SymbiosisMasterPage.SymbiosisMasterPageViewModel._deleteDropDownInitialValues(reduced);
    }
public PhysicalForm:
    any;
}

export class PhysicalForm_PhysicalFormViewModel extends BaseClass.ViewModel  {
    public constructor() {
        super();
    }


    public static _lightCast(instance: any): any {
        if (instance == null) return;

        return instance;
    }

    public static _initializeFrom(original: PhysicalForm_PhysicalFormViewModel, ignoreReadOnlyProperties: boolean = false, context = new Joove.DTOHelper()): PhysicalForm_PhysicalFormViewModel {
        if(original == null) return null;
        // if (context.Has(original)) {
        //    return context.Get(original);
        // }
var result:
        PhysicalForm_PhysicalFormViewModel = new PhysicalForm_PhysicalFormViewModel();
        if (context != null && context.fillDb == true) {
            context.addToDb(original);
        }
        result._hydratePhysicalForm_PhysicalFormViewModel(original, ignoreReadOnlyProperties, context);
        // context.Add(original, result);
        return result;
    }


    public _hydratePhysicalForm_PhysicalFormViewModel(original: PhysicalForm_PhysicalFormViewModel, ignoreReadOnlyProperties: boolean, context = new Joove.DTOHelper()): void {
        if(original == null) return;


        if(original._key !== undefined) this._key = original._key;
        if(original._clientKey !== undefined) this._clientKey = original._clientKey;
        if(original._originalTypeClassName !== undefined) this._originalTypeClassName = original._originalTypeClassName;
        if(original._typeHash !== undefined) this._typeHash = original._typeHash;

        if(original.Id !== undefined) this.Id = original.Id;
        if(original.Code !== undefined) this.Code = original.Code;
        if(original.Value !== undefined) this.Value = original.Value;

        this._reduceData = function(ignoreReadOnlyProperties: boolean) {
            var reduced = PhysicalForm_PhysicalFormViewModel._initializeFrom(this, ignoreReadOnlyProperties);

            return reduced;
        };
    } /* end _initializeFrom() */


    public _reduceData(ignoreReadOnlyProperties: boolean): PhysicalForm_PhysicalFormViewModel {
        var reduced = PhysicalForm_PhysicalFormViewModel._initializeFrom(this, ignoreReadOnlyProperties);

        return reduced;
    }
public Id:
    any;
public Code:
    any;
public Value:
    any;
}

}
