// Copyright (c) CLMS UK. All rights reserved.
// Licensed under the Custom License. See LICENSE file in the project root for full license information.
// This was autogenerated by zAppDev.
namespace DigicircMatchmaking.ViewModels.ResourceForm {
export class ResourceFormViewModel extends BaseClass.ViewModel  {
    public constructor() {
        super();
    }


    public static _lightCast(instance: any): any {
        if (instance == null) return;

        if(instance.Product != null)
            instance.Product = Product_ProductViewModel._lightCast(instance.Product);
        return instance;
    }

    public static _initializeFrom(original: ResourceFormViewModel, ignoreReadOnlyProperties: boolean = false, context = new Joove.DTOHelper()): ResourceFormViewModel {
        if(original == null) return null;
        // if (context.Has(original)) {
        //    return context.Get(original);
        // }
var result:
        ResourceFormViewModel = new ResourceFormViewModel();
        if (context != null && context.fillDb == true) {
            context.addToDb(original);
        }
        result._hydrateResourceFormViewModel(original, ignoreReadOnlyProperties, context);
        // context.Add(original, result);
        return result;
    }


    public _hydrateResourceFormViewModel(original: ResourceFormViewModel, ignoreReadOnlyProperties: boolean, context = new Joove.DTOHelper()): void {
        if(original == null) return;


        if(original._key !== undefined) this._key = original._key;
        if(original._clientKey !== undefined) this._clientKey = original._clientKey;
        if(original._originalTypeClassName !== undefined) this._originalTypeClassName = original._originalTypeClassName;
        if(original._typeHash !== undefined) this._typeHash = original._typeHash;


        if(original.Product !== undefined) this.Product = Product_ProductViewModel._initializeFrom(original.Product, ignoreReadOnlyProperties, context);
        if(original.ActorId !== undefined) this.ActorId = original.ActorId;
        if (original.DropdownBox4__InitialSelection !== undefined) this.DropdownBox4__InitialSelection = original.DropdownBox4__InitialSelection;
        if (original.DropdownBox__InitialSelection !== undefined) this.DropdownBox__InitialSelection = original.DropdownBox__InitialSelection;
        this.DropdownBox4SelectedItemKeys = original.DropdownBox4SelectedItemKeys;
        this.DropdownBoxSelectedItemKeys = original.DropdownBoxSelectedItemKeys;

        this._reduceData = function(ignoreReadOnlyProperties: boolean) {
            var reduced = ResourceFormViewModel._initializeFrom(this, ignoreReadOnlyProperties);
            ResourceFormViewModel._deleteDropDownInitialValues(reduced);
            return reduced;
        };
    } /* end _initializeFrom() */


    public _reduceData(ignoreReadOnlyProperties: boolean): ResourceFormViewModel {
        var reduced = ResourceFormViewModel._initializeFrom(this, ignoreReadOnlyProperties);
        ResourceFormViewModel._deleteDropDownInitialValues(reduced);
        return reduced;
    }

    public static _deleteDropDownInitialValues(reduced: ResourceFormViewModel) {
        if (reduced == null) return;

        delete reduced.DropdownBox4__InitialSelection;
        delete reduced.DropdownBox__InitialSelection;


    }
public Product:
    any;
public ActorId:
    any;
public DropdownBox4__InitialSelection:
    any;
public DropdownBox__InitialSelection:
    any;
public DropdownBox4SelectedItemKeys:
    any[];
public DropdownBoxSelectedItemKeys:
    any[];
}

export class Product_ProductViewModel extends BaseClass.ViewModel  {
    public constructor() {
        super();
    }


    public static _lightCast(instance: any): any {
        if (instance == null) return;

        if(instance.ValidFrom != null) instance.ValidFrom = new Date(instance.ValidFrom);
        if(instance.ValidTo != null) instance.ValidTo = new Date(instance.ValidTo);
        if(instance.Resource != null)
            instance.Resource = Product_Product_Resource_MaterialViewModel._lightCast(instance.Resource);
        if(instance.Site != null)
            instance.Site = Product_Product_Site_AddressViewModel._lightCast(instance.Site);
        return instance;
    }

    public static _initializeFrom(original: Product_ProductViewModel, ignoreReadOnlyProperties: boolean = false, context = new Joove.DTOHelper()): Product_ProductViewModel {
        if(original == null) return null;
        // if (context.Has(original)) {
        //    return context.Get(original);
        // }
var result:
        Product_ProductViewModel = new Product_ProductViewModel();
        if (context != null && context.fillDb == true) {
            context.addToDb(original);
        }
        result._hydrateProduct_ProductViewModel(original, ignoreReadOnlyProperties, context);
        // context.Add(original, result);
        return result;
    }


    public _hydrateProduct_ProductViewModel(original: Product_ProductViewModel, ignoreReadOnlyProperties: boolean, context = new Joove.DTOHelper()): void {
        if(original == null) return;


        if(original._key !== undefined) this._key = original._key;
        if(original._clientKey !== undefined) this._clientKey = original._clientKey;
        if(original._originalTypeClassName !== undefined) this._originalTypeClassName = original._originalTypeClassName;
        if(original._typeHash !== undefined) this._typeHash = original._typeHash;

        if (original._versionTimestamp !== undefined) this._versionTimestamp = original._versionTimestamp;
        if(original.Id !== undefined) this.Id = original.Id;
        if(original.IsDesired !== undefined) this.IsDesired = original.IsDesired;
        if(original.Quantity !== undefined) this.Quantity = original.Quantity;
        if(!CLMS.Framework.String.IsNullOrEmpty(original.ValidFrom)) this.ValidFrom = new Date(original.ValidFrom);
        if(!CLMS.Framework.String.IsNullOrEmpty(original.ValidTo)) this.ValidTo = new Date(original.ValidTo);

        if(original.Resource !== undefined) this.Resource = Product_Product_Resource_MaterialViewModel._initializeFrom(original.Resource, ignoreReadOnlyProperties, context);

        if(original.Site !== undefined) this.Site = Product_Product_Site_AddressViewModel._initializeFrom(original.Site, ignoreReadOnlyProperties, context);

        this._reduceData = function(ignoreReadOnlyProperties: boolean) {
            var reduced = Product_ProductViewModel._initializeFrom(this, ignoreReadOnlyProperties);

            return reduced;
        };
    } /* end _initializeFrom() */


    public _reduceData(ignoreReadOnlyProperties: boolean): Product_ProductViewModel {
        var reduced = Product_ProductViewModel._initializeFrom(this, ignoreReadOnlyProperties);

        return reduced;
    }
public Id:
    any;
public IsDesired:
    any;
public Quantity:
    any;
public ValidFrom:
    any;
public ValidTo:
    any;
public Resource:
    any;
public Site:
    any;
    public _versionTimestamp?: string;
}

export class Product_Product_Resource_MaterialViewModel extends BaseClass.ViewModel  {
    public constructor() {
        super();
    }


    public static _lightCast(instance: any): any {
        if (instance == null) return;

        return instance;
    }

    public static _initializeFrom(original: Product_Product_Resource_MaterialViewModel, ignoreReadOnlyProperties: boolean = false, context = new Joove.DTOHelper()): Product_Product_Resource_MaterialViewModel {
        if(original == null) return null;
        // if (context.Has(original)) {
        //    return context.Get(original);
        // }
var result:
        Product_Product_Resource_MaterialViewModel = new Product_Product_Resource_MaterialViewModel();
        if (context != null && context.fillDb == true) {
            context.addToDb(original);
        }
        result._hydrateProduct_Product_Resource_MaterialViewModel(original, ignoreReadOnlyProperties, context);
        // context.Add(original, result);
        return result;
    }


    public _hydrateProduct_Product_Resource_MaterialViewModel(original: Product_Product_Resource_MaterialViewModel, ignoreReadOnlyProperties: boolean, context = new Joove.DTOHelper()): void {
        if(original == null) return;


        if(original._key !== undefined) this._key = original._key;
        if(original._clientKey !== undefined) this._clientKey = original._clientKey;
        if(original._originalTypeClassName !== undefined) this._originalTypeClassName = original._originalTypeClassName;
        if(original._typeHash !== undefined) this._typeHash = original._typeHash;

        if (original._versionTimestamp !== undefined) this._versionTimestamp = original._versionTimestamp;
        if(original.Description !== undefined) this.Description = original.Description;
        if(original.HsSpecific !== undefined) this.HsSpecific = original.HsSpecific;
        if(original.Id !== undefined) this.Id = original.Id;
        if(original.Name !== undefined) this.Name = original.Name;

        this._reduceData = function(ignoreReadOnlyProperties: boolean) {
            var reduced = Product_Product_Resource_MaterialViewModel._initializeFrom(this, ignoreReadOnlyProperties);

            return reduced;
        };
    } /* end _initializeFrom() */


    public _reduceData(ignoreReadOnlyProperties: boolean): Product_Product_Resource_MaterialViewModel {
        var reduced = Product_Product_Resource_MaterialViewModel._initializeFrom(this, ignoreReadOnlyProperties);

        return reduced;
    }
public Description:
    any;
public HsSpecific:
    any;
public Id:
    any;
public Name:
    any;
    public _versionTimestamp?: string;
}

export class Product_Product_Site_AddressViewModel extends BaseClass.ViewModel  {
    public constructor() {
        super();
    }


    public static _lightCast(instance: any): any {
        if (instance == null) return;

        return instance;
    }

    public static _initializeFrom(original: Product_Product_Site_AddressViewModel, ignoreReadOnlyProperties: boolean = false, context = new Joove.DTOHelper()): Product_Product_Site_AddressViewModel {
        if(original == null) return null;
        // if (context.Has(original)) {
        //    return context.Get(original);
        // }
var result:
        Product_Product_Site_AddressViewModel = new Product_Product_Site_AddressViewModel();
        if (context != null && context.fillDb == true) {
            context.addToDb(original);
        }
        result._hydrateProduct_Product_Site_AddressViewModel(original, ignoreReadOnlyProperties, context);
        // context.Add(original, result);
        return result;
    }


    public _hydrateProduct_Product_Site_AddressViewModel(original: Product_Product_Site_AddressViewModel, ignoreReadOnlyProperties: boolean, context = new Joove.DTOHelper()): void {
        if(original == null) return;


        if(original._key !== undefined) this._key = original._key;
        if(original._clientKey !== undefined) this._clientKey = original._clientKey;
        if(original._originalTypeClassName !== undefined) this._originalTypeClassName = original._originalTypeClassName;
        if(original._typeHash !== undefined) this._typeHash = original._typeHash;

        if (original._versionTimestamp !== undefined) this._versionTimestamp = original._versionTimestamp;
        if(original.FullAddress !== undefined) this.FullAddress = original.FullAddress;
        if(original.Id !== undefined) this.Id = original.Id;
        if(original.Latitude !== undefined) this.Latitude = original.Latitude;
        if(original.Longitude !== undefined) this.Longitude = original.Longitude;
        if(original.Number !== undefined) this.Number = original.Number;
        if(original.StreetName !== undefined) this.StreetName = original.StreetName;
        if(original.Town !== undefined) this.Town = original.Town;
        if(original.Zip !== undefined) this.Zip = original.Zip;

        this._reduceData = function(ignoreReadOnlyProperties: boolean) {
            var reduced = Product_Product_Site_AddressViewModel._initializeFrom(this, ignoreReadOnlyProperties);

            return reduced;
        };
    } /* end _initializeFrom() */


    public _reduceData(ignoreReadOnlyProperties: boolean): Product_Product_Site_AddressViewModel {
        var reduced = Product_Product_Site_AddressViewModel._initializeFrom(this, ignoreReadOnlyProperties);

        return reduced;
    }
public FullAddress:
    any;
public Id:
    any;
public Latitude:
    any;
public Longitude:
    any;
public Number:
    any;
public StreetName:
    any;
public Town:
    any;
public Zip:
    any;
    public _versionTimestamp?: string;
}

}
