// Copyright (c) CLMS UK. All rights reserved.
// Licensed under the Custom License. See LICENSE file in the project root for full license information.
// This was autogenerated by zAppDev.
using System;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Linq;
using DigicircMatchmaking.BO;
using DigicircMatchmaking.UI.Controllers.GraphExportForm;
using AppCode;
using zAppDev.DotNet.Framework.Data;
using zAppDev.DotNet.Framework.Utilities;
using zAppDev.DotNet.Framework.Data.Domain;
using zAppDev.DotNet.Framework.Mvc;
using zAppDev.DotNet.Framework.Locales;
using System.ComponentModel.DataAnnotations;
using DigicircMatchmaking.UI.ViewModels.MasterPage;
using DigicircMatchmaking.UI.Controllers.MasterPage;
namespace DigicircMatchmaking.UI.ViewModels.GraphExportForm
{
    public class GraphExportFormViewModel : MasterPageViewModel
    {


        public GraphExportFormViewModel()
        {
        }


        public override void Evict()
        {
            var manager = MiniSessionManager.Instance;
        }

    }


    [OriginalType(typeof(DigicircMatchmaking.UI.ViewModels.GraphExportForm.GraphExportFormViewModel))]
    public class GraphExportFormViewModelDTO : MasterPageViewModelDTO, IViewModelDTO<DigicircMatchmaking.UI.ViewModels.GraphExportForm.GraphExportFormViewModel>
    {

        [JsonConstructor]
        public GraphExportFormViewModelDTO() { }
        public GraphExportFormViewModelDTO(DigicircMatchmaking.UI.ViewModels.GraphExportForm.GraphExportFormViewModel original, bool parentIsDirty = false)  : base(original)
        {
            if (original == null) return;
        }
        public override string _originalTypeClassName => typeof(DigicircMatchmaking.UI.ViewModels.GraphExportForm.GraphExportFormViewModel).FullName;

        public new DigicircMatchmaking.UI.ViewModels.GraphExportForm.GraphExportFormViewModel GetModel()
        {
            var alreadySeenInstance = DTOHelper.GetSeenModelInstance<DigicircMatchmaking.UI.ViewModels.GraphExportForm.GraphExportFormViewModel>(_clientKey, _originalTypeClassName, _baseClasses);
            if (alreadySeenInstance != null) return alreadySeenInstance;
            return new DigicircMatchmaking.UI.ViewModels.GraphExportForm.GraphExportFormViewModel();
        }
        new  public DigicircMatchmaking.UI.ViewModels.GraphExportForm.GraphExportFormViewModel Convert()
        {
            var original = GetModel();
            if (original == null)
            {
                original = new DigicircMatchmaking.UI.ViewModels.GraphExportForm.GraphExportFormViewModel();
            }
            DTOHelper.UpdateSeenModelInstances(this, original);
            Hydrate(original);
            return original;
        }
        public void Hydrate(DigicircMatchmaking.UI.ViewModels.GraphExportForm.GraphExportFormViewModel original)
        {
            if (original == null) return;
            base.Hydrate(original);
        }
    }



}
