// Copyright (c) CLMS UK. All rights reserved.
// Licensed under the Custom License. See LICENSE file in the project root for full license information.
// This was autogenerated by zAppDev.
using System;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Linq;
using DigicircMatchmaking.BO;
using DigicircMatchmaking.UI.Controllers.ServicesForm;
using AppCode;
using zAppDev.DotNet.Framework.Data;
using zAppDev.DotNet.Framework.Utilities;
using zAppDev.DotNet.Framework.Data.Domain;
using zAppDev.DotNet.Framework.Mvc;
using zAppDev.DotNet.Framework.Locales;
using System.ComponentModel.DataAnnotations;
using DigicircMatchmaking.UI.ViewModels.MasterPage;
using DigicircMatchmaking.UI.Controllers.MasterPage;
namespace DigicircMatchmaking.UI.ViewModels.ServicesForm
{
    public class ServicesFormViewModel : MasterPageViewModel
    {
        public DigicircMatchmaking.BO.Services Services;


        public ServicesFormViewModel()
        {
            Services = new DigicircMatchmaking.BO.Services();
        }


        public override void Evict()
        {
            var manager = MiniSessionManager.Instance;
            if (manager.Session.Contains(Services))
            {
                manager.Session.Evict(Services);
            }
        }

    }


    [OriginalType(typeof(DigicircMatchmaking.UI.ViewModels.ServicesForm.ServicesFormViewModel))]
    public class ServicesFormViewModelDTO : MasterPageViewModelDTO, IViewModelDTO<DigicircMatchmaking.UI.ViewModels.ServicesForm.ServicesFormViewModel>
    {

        [JsonConstructor]
        public ServicesFormViewModelDTO() { }
        public ServicesFormViewModelDTO(DigicircMatchmaking.UI.ViewModels.ServicesForm.ServicesFormViewModel original, bool parentIsDirty = false)  : base(original)
        {
            if (original == null) return;
            Services = original.Services == null ? null : new Services_ServicesDTO(original.Services);
        }
        public Services_ServicesDTO Services;
        public override string _originalTypeClassName => typeof(DigicircMatchmaking.UI.ViewModels.ServicesForm.ServicesFormViewModel).FullName;

        public new DigicircMatchmaking.UI.ViewModels.ServicesForm.ServicesFormViewModel GetModel()
        {
            var alreadySeenInstance = DTOHelper.GetSeenModelInstance<DigicircMatchmaking.UI.ViewModels.ServicesForm.ServicesFormViewModel>(_clientKey, _originalTypeClassName, _baseClasses);
            if (alreadySeenInstance != null) return alreadySeenInstance;
            return new DigicircMatchmaking.UI.ViewModels.ServicesForm.ServicesFormViewModel();
        }
        new  public DigicircMatchmaking.UI.ViewModels.ServicesForm.ServicesFormViewModel Convert()
        {
            var original = GetModel();
            if (original == null)
            {
                original = new DigicircMatchmaking.UI.ViewModels.ServicesForm.ServicesFormViewModel();
            }
            DTOHelper.UpdateSeenModelInstances(this, original);
            Hydrate(original);
            return original;
        }
        public void Hydrate(DigicircMatchmaking.UI.ViewModels.ServicesForm.ServicesFormViewModel original)
        {
            if (original == null) return;
            base.Hydrate(original);
            original.Services = Services == null
                                ? null
                                : Services.Convert();
        }
    }

    [OriginalType(typeof(DigicircMatchmaking.BO.Services))]
    public class Services_ServicesDTO : ViewModelDTOBase, IViewModelDTO<DigicircMatchmaking.BO.Services>
    {

        [JsonConstructor]
        public Services_ServicesDTO() { }
        public Services_ServicesDTO(DigicircMatchmaking.BO.Services original, bool parentIsDirty = false)
        {
            if (original == null) return;
            _key = original.Id as object;
            Id = original.Id;
            Code = original.Code;
            Value = original.Value;
            _clientKey = DTOHelper.GetClientKey(original, Id);
        }
        public int? Id;
        public new object _key
        {
            get;
            set;
        }
        public string Code;
        public string Value;
        public override string _originalTypeClassName => typeof(DigicircMatchmaking.BO.Services).FullName;
        public override List<string> _baseClasses => new List<string> {typeof(DigicircMatchmaking.BO.ValueType).FullName};
        public DigicircMatchmaking.BO.Services GetModel()
        {
            var alreadySeenInstance = DTOHelper.GetSeenModelInstance<DigicircMatchmaking.BO.Services>(_clientKey, _originalTypeClassName, _baseClasses);
            if (alreadySeenInstance != null) return alreadySeenInstance;
            if (_key == null) return null;
            var rawKey = _key.ToString();
            var parsedKey = int.Parse(rawKey);
            if (parsedKey == default(int) || Equals(parsedKey, default(int)))
            {
                return new DigicircMatchmaking.BO.Services();
            }
            return new DAL.Repository().GetById<DigicircMatchmaking.BO.Services>(parsedKey, false, false);
        }
        public DigicircMatchmaking.BO.Services Convert()
        {
            var original = GetModel();
            if (original == null)
            {
                original = new DigicircMatchmaking.BO.Services();
            }
            DTOHelper.UpdateSeenModelInstances(this, original);
            Hydrate(original);
            return original;
        }
        public void Hydrate(DigicircMatchmaking.BO.Services original)
        {
            if (original == null) return;
            original.Id = Id ?? 0;
            original.Code = Code;
            original.Value = Value;
        }
        public static Services_ServicesDTO GetInstance(object key, string jbID)
        {
            if (key == null) return null;
            var rawKey = key.ToString();
            var parsedKey = int.Parse(rawKey);
            var foundEntry = new DAL.Repository().GetById<DigicircMatchmaking.BO.Services>(parsedKey, true, false);
            if(foundEntry != null)
            {
                return new Services_ServicesDTO(foundEntry);
            }
            return null;
        }
    }



}
