// Copyright (c) CLMS UK. All rights reserved.
// Licensed under the Custom License. See LICENSE file in the project root for full license information.
// This was autogenerated by zAppDev.
using System;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Linq;
using DigicircMatchmaking.BO;
using DigicircMatchmaking.UI.Controllers.SignOutPage;
using AppCode;
using zAppDev.DotNet.Framework.Data;
using zAppDev.DotNet.Framework.Utilities;
using zAppDev.DotNet.Framework.Data.Domain;
using zAppDev.DotNet.Framework.Mvc;
using zAppDev.DotNet.Framework.Locales;
using System.ComponentModel.DataAnnotations;
using DigicircMatchmaking.UI.ViewModels.MasterPage;
using DigicircMatchmaking.UI.Controllers.MasterPage;
namespace DigicircMatchmaking.UI.ViewModels.SignOutPage
{
    public class SignOutPageViewModel : MasterPageViewModel
    {


        public SignOutPageViewModel()
        {
        }


        public override void Evict()
        {
            var manager = MiniSessionManager.Instance;
        }

    }


    [OriginalType(typeof(DigicircMatchmaking.UI.ViewModels.SignOutPage.SignOutPageViewModel))]
    public class SignOutPageViewModelDTO : MasterPageViewModelDTO, IViewModelDTO<DigicircMatchmaking.UI.ViewModels.SignOutPage.SignOutPageViewModel>
    {

        [JsonConstructor]
        public SignOutPageViewModelDTO() { }
        public SignOutPageViewModelDTO(DigicircMatchmaking.UI.ViewModels.SignOutPage.SignOutPageViewModel original, bool parentIsDirty = false)  : base(original)
        {
            if (original == null) return;
        }
        public override string _originalTypeClassName => typeof(DigicircMatchmaking.UI.ViewModels.SignOutPage.SignOutPageViewModel).FullName;

        public new DigicircMatchmaking.UI.ViewModels.SignOutPage.SignOutPageViewModel GetModel()
        {
            var alreadySeenInstance = DTOHelper.GetSeenModelInstance<DigicircMatchmaking.UI.ViewModels.SignOutPage.SignOutPageViewModel>(_clientKey, _originalTypeClassName, _baseClasses);
            if (alreadySeenInstance != null) return alreadySeenInstance;
            return new DigicircMatchmaking.UI.ViewModels.SignOutPage.SignOutPageViewModel();
        }
        new  public DigicircMatchmaking.UI.ViewModels.SignOutPage.SignOutPageViewModel Convert()
        {
            var original = GetModel();
            if (original == null)
            {
                original = new DigicircMatchmaking.UI.ViewModels.SignOutPage.SignOutPageViewModel();
            }
            DTOHelper.UpdateSeenModelInstances(this, original);
            Hydrate(original);
            return original;
        }
        public void Hydrate(DigicircMatchmaking.UI.ViewModels.SignOutPage.SignOutPageViewModel original)
        {
            if (original == null) return;
            base.Hydrate(original);
        }
    }



}
