// Copyright (c) CLMS UK. All rights reserved.
// Licensed under the Custom License. See LICENSE file in the project root for full license information.
// This was autogenerated by zAppDev.
var directiveScopeReadyLimit = 10;
var directiveScopeReadyTimeout = 200;
interface Window { scope_KnowledgeHub: DigicircMatchmaking.Controllers.IKnowledgeHubScope; }
namespace DigicircMatchmaking.Controllers {
const KnowledgeHubConditionalFormattings = [
        ];
const KnowledgeHubDataValidations = [
                                    ];
const KnowledgeHubCalculatedExpressions = [
        ];

// Datasets Column Info
export var MaterialDataSet_ColumnInfo = [new Joove.ColumnInfo("Name", "string", null, false),
           new Joove.ColumnInfo("original", "Material", null, false)];
window["MaterialDataSet_ColumnInfo"] = MaterialDataSet_ColumnInfo;

export class KnowledgeHubProductDatasetViewModelDataset extends Joove.IViewModelDataset<any> {


    constructor(model, partialViewControlName: string = null) {
        super(model, partialViewControlName);
        this.limit = 0;
    }

    Filter(inputs: any): (DataItem: any, index: number, items: Array<any>) => boolean {
        var $scope = { model: this.model };

        return (DataItem, index, items) => {
            return true;


        };
    }

    PackInputs($control: JQuery): any {
        return Joove.DatasourceManager.getDatasetControlInputs($control);
    }

    Sort(items: Joove.ViewModelCollection): Joove.ViewModelCollection {
        return items;
    }

    GetSource(parents: number[]): Joove.ViewModelCollection {
        return this.model.Actor.CircularEconomyRequirements.DesiredResources;
    }


}



// Datasets Projection Shemas
window["TextBox_ProjectionScema"] = {};
window["TextBox1_ProjectionScema"] = {};


export interface IKnowledgeHubScope extends Joove.IWebPageScope {
model:
    DigicircMatchmaking.ViewModels.KnowledgeHub.KnowledgeHubViewModel;
_partialModelStructure:
    any;
    _validations?: {
summary: Array<Joove.Validation.BindingEntry>,

    },
    _masterValidations?: any;
}

class KnowledgeHubController {
private timeoutDelayLockButtonClicked:
    any;


    private controllerActionFinished = (resetDirty: boolean) => {
        //window.scope_KnowledgeHub.model = window.scope_KnowledgeHub.dehydrate();
        //window.scope_SymbiosisMasterPage.model = window.scope_KnowledgeHub.model;
        DigicircMatchmaking.ViewModels.KnowledgeHub.KnowledgeHubViewModel._lightCast(window.scope_KnowledgeHub.model);
        // Joove.Common.applyScope(window.scope_KnowledgeHub);
        if (resetDirty) {
            window._context.isDirty = false;
        }
        window._ruleEngine.update(Joove.EvaluationTimes.OnChange);
    }

    constructor(private $scope: IKnowledgeHubScope, $timeout: ng.ITimeoutService) {
        window.scope_KnowledgeHub = $scope;
        $scope.$onControlChanged = function (event, newValue, dontMakeDirty) {
            Joove.Core.onChange(event.target, newValue, dontMakeDirty)
        }

        $scope.dehydrate = (context = null) => DigicircMatchmaking.ViewModels.KnowledgeHub.KnowledgeHubViewModel._initializeFrom($scope.model, context);
        $scope._validationsMaster =  window.scope_SymbiosisMasterPage._validations;
        $scope._validations = { summary:
                                [],
                              };

        this.init($scope, $timeout);
        $timeout(() => {

            window._ruleEngine.update(Joove.EvaluationTimes.OnLoad, null, () => {

                $("body").fadeIn(200);

            });
        });

    }

    init($scope: IKnowledgeHubScope, $timeout: ng.ITimeoutService) {


        $scope.model = DigicircMatchmaking.ViewModels.KnowledgeHub.KnowledgeHubViewModel._initializeFrom(window.viewDTO.Model);

        window.scope_SymbiosisMasterPage.model = $scope.model;

        new Joove.ReferencesReconstructor().reconstructReferences($scope.model);
        $scope.trackObject = obj => Joove.Common.trackObject(obj);




        //}

        $.connection['eventsHub'].on('__connectedEvent', () => { });

        $.connection['eventsHub'].on('forcePageReload', () => {
            window.onbeforeunload = null;
            setTimeout(() => {
                window.location.reload();
            }, 3000);
        });
        $.connection.hub.start().then(() => {
            Joove.Common.getScope().connectedToSignals();
            Joove.Common.getMasterScope().connectedToSignals();

        });
        $scope.connectedToSignals = () => {
        }
// Event Listeners
        $scope.events = {
        };
        $scope.expressions = {
        }
// Dataset Handler
        $scope.datasets = {

ProductDataset:
            (partialViewControlName: string = null) => {
                return new DigicircMatchmaking.Controllers.KnowledgeHubProductDatasetViewModelDataset($scope.model, partialViewControlName);
            },
        };
// Controller actions
        $scope.actions = {
Index:
            async (_cb, _modalOptions, _e) => {
                Joove.Common.autocompleteFix();


                Joove.Core.executeRedirectControllerAction("KnowledgeHub", "Index", "GET", [], {}, _modalOptions);
            },
Search:
            async (_cb, _modalOptions, _e) => {
                Joove.Common.autocompleteFix();

                const implementation = async (): Promise<any> => {
                    eval("update('" + Joove.Common.safeNumber(Joove.Common.nullSafe<any>(() => window["scope_KnowledgeHub"].model.Waste.Id, 0)) + "', '" + Joove.Common.safeNumber(Joove.Common.nullSafe<any>(() => window["scope_KnowledgeHub"].model.Product.Id, 0)) + "')");


                    // Joove.Common.applyScope(window.scope_KnowledgeHub);
                }


                let spamHelper = new Joove.SpamControlHelper(_e);
                spamHelper.Disable();
                await implementation();
                spamHelper.Enable();
                this.controllerActionFinished(false);
            },
        };
// Events
        $scope.eventCallbacks = {
ButtonClicked:
            (e, DataItem, _parents) => {


                if (e != null) {
                    e.stopPropagation();
                    e.preventDefault();
                }

                if (this.timeoutDelayLockButtonClicked != null) {
                    $timeout.cancel(this.timeoutDelayLockButtonClicked);
                }

                this.timeoutDelayLockButtonClicked = $timeout(() => {
                    Joove.Common.setControlKeyPressed(e, 0); Joove.Common.setLastClickedElement(e);

                    Joove.Validation.Manager.validateFormAndExecute(() => {
                        $scope.actions.Search(null, null, e);
}, { groups: [Joove.Validation.Constants.ALL_GROUPS], withDataValidationsCheck: false, withRequiredFieldsCheck: false });
                }, 0);
            },

        };

// Rules
        window._ruleEngine.addDataValidations(KnowledgeHubDataValidations);
        window._ruleEngine.addConditionalFormattings(KnowledgeHubConditionalFormattings);
        window._ruleEngine.addCalculatedExpressions(KnowledgeHubCalculatedExpressions);

        window._commander.executeCommands(window.viewDTO.ClientCommands);
        window.viewDTO.ClientCommands = [];

        Joove.Common.setNumberLocalizationSettings();
        Joove.DeveloperApi.init($scope as any, window.scope_SymbiosisMasterPage as any);
        window.$formExtend && window.$formExtend();
        window.$onFormLoaded && window.$onFormLoaded();
    }
}
angular.module("Application").controller("KnowledgeHubController", ["$scope", "$timeout", KnowledgeHubController] as Array<string>);
}
