<%
  Copyright (c) CLMS UK. All rights reserved.
  Licensed under the Custom License. See LICENSE file in the project root for full license information.
  This was autogenerated by zAppDev.
%>

<%@ Application Codebehind="Global.asax.cs" Inherits="DigicircMatchmaking.Web.Global" Language ="C#" %>